language: java
jdk:
- oraclejdk8

script: mvn -f ./plugins/de.tudresden.slr.parent/pom.xml clean package

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/features/de.tudresden.slr.product/target/products/slr-toolkit*
  on:
    tags: true
    all_branches: true